## Phase 3.22

# Linear Algebra

## Objectives

1. Why Linear Algebra?
2. Data Types for Linear Algebra
3. Operations on Vectors and Matrices
    - Addition and Subtraction
    - Broadcasting
    - Multiplication (3 kinds)
    - Division
4. Systems of Linear Equations
5. Linear Regression with Linear Algebra


# Part 1. Why Linear Algebra?

Linear Algebra is the basis of many machine learning models.

Data is usually already set up into a matrix by default!

<img src= "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/dataset.jpeg">

It can be used to model complicated things like language

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/Word-Vectors.png">

Important for image compression and recognition

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources//images.gif">

Recommendation engines are able to make much more sophisticated recommendations by using linear algebra in conjunction with user and content data.

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/netflix.png">





<img src="https://github.com/yishuen/studygroups-092820ft/blob/master/phase-3/resources/linalgmeme.png?raw=1" alt="drawing" width="400"/>

# Part 2: Data Types for Linear Algebra

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/datadogs.jpg">

* Scalars only have magnitude.

* A vector is an array with **magnitude and direction**. The coordinates of a vector represent where the tip of the vector would be if you travelled from the origin, and the magnitude of a vector would be its length in space.

* Matrices can be interpreted differently in different contexts but it's often used to represent multiple simultaneous vectors. 

* A vector or matrix can be multiplied by a scalar to create a change in **scale** and/or direction.

* Tensors are made up of matrices with the same dimensions.

Vectors, matrices and tensors are represented by NumPy arrays. **Not lists!!!** We can use `np.array.shape` to explore the dimensions of these data structures.


In [1]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6])
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(vector)
print('vector shape:', vector.shape, '\n')
print(matrix1)
print('matrix1 shape:', matrix1.shape, '\n')
print(matrix2)
print('matrix2 shape:', matrix2.shape, '\n')
print(tensor)
print('tensor shape:', tensor.shape, '\n')

[1 2 3 4 5 6]
vector shape: (6,) 

[[1 2 3]
 [4 5 6]]
matrix1 shape: (2, 3) 

[[1 2]
 [3 4]
 [5 6]]
matrix2 shape: (3, 2) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
tensor shape: (2, 2, 2) 



In [2]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
tensor[1], tensor[1].shape

(array([[5, 6],
        [7, 8]]),
 (2, 2))

In [5]:
tensor[0][0][1]

2

In [6]:
tensor[0, 0, 1]

2

### Magnitude of a vector

$length = \|v \| = \sqrt{v \cdot v} = (v_{1}^2 + v_{2}^2 + \cdot \cdot \cdot \cdot + v_{n}^2)$


In [7]:
np.linalg.norm(vector)

9.539392014169456

### Transposing

Calling `.transpose()` on an array **reverses** its shape order.

In [8]:
print(matrix1)
print('matrix1 shape:', matrix1.shape, '\n')

# transposed
print(matrix1.transpose(), '\n')
print('matrix1.transpose() shape:', matrix1.transpose().shape)

[[1 2 3]
 [4 5 6]]
matrix1 shape: (2, 3) 

[[1 4]
 [2 5]
 [3 6]] 

matrix1.transpose() shape: (3, 2)


In [9]:
tensor2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], 
           [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

print(tensor2, '\n')
print('shape of tensor2: ', tensor2.shape, '\n')

# transposed
print(tensor2.transpose(), '\n')
print('shape of tensor2.transpose(): ', tensor2.transpose().shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]] 

shape of tensor2:  (2, 4, 3) 

[[[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]

 [[ 3 15]
  [ 6 18]
  [ 9 21]
  [12 24]]] 

shape of tensor2.transpose():  (3, 4, 2)


# Part 3: Operations on Vectors and Matrices

## a. Addition & Subtraction

For addition and subtraction of vectors, matrices and even tensors, as long as the dimensions are equal the operation occurs **element-wise**. This means given two vectors `v` and `w`:

$ \vec{v} = \begin{bmatrix}v_{1} \\v_{2}\end{bmatrix} $


$ \vec{w} = \begin{bmatrix}w_{1} \\w_{2}\end{bmatrix} $

$ \vec{v} + \vec{w} = \begin{bmatrix}v_{1} + w_{1} \\v_{2} + w_{2}\end{bmatrix} $

In [10]:
v = np.array([2, 4])
w = np.array([3, 2])

v - w

array([-1,  2])

## b. Broadcasting

NumPy arrays allow for something known as **broadcasting**, which happens when you perform operations across arrays with different number of dimensions. NumPy makes duplicates of the lower-dimension array **as long as the higher-dimension array *contains* the same shape** in order to execute the operation. Order of the `.shape` tuple matters!

In [11]:
scalar = 4
print(vector)

print(vector + scalar)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


In [12]:
v1 = np.array([1, 0, 1])
m1 = np.array([[1, 2], [3, 4], [5, 6]])
m1 - v1

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [13]:
m1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
m1.T - v1

array([[0, 3, 4],
       [1, 4, 5]])

What shapes of matrices and vectors can be broadcast onto `tensor2`?

In [15]:
print(tensor2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [16]:
tensor2.shape

(2, 4, 3)

In [19]:
np.array([1]).shape
# tensor2 + np.array([1])

(1,)

In [30]:
np.array([1,2,3]).shape
# print(tensor2)
# tensor2 + np.array([1,2,3])

(3,)

In [37]:
# Will not work!
# np.array([1,2,3,4]).shape
# tensor2 + np.array([1,2,3,4])

In [36]:
stamp = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
tensor2 + stamp

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]],

       [[14, 16, 18],
        [20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [ ]:
test = np.array([
    [1,2,3],
    [4,5,6]
])

test + tensor2

## c. Multiplication

### i. Hadamard Product

Hadamard Multiplication occurs element-wise, and therefore can only occur between matrices of the same shape **OR** when broadcasting can occur. The Hadamard product is very easy in NumPy: just use `*`!


\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\circ
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} & a_{1,2}\times b_{1,2} \\
a_{2,1}\times b_{2,1} & a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}


In [38]:
# Use NumPy to calculate the Hadamard product of
# [[1, 2], [1, 2]] and [[3, 4], [5, 9]]
a = np.array([[1, 2], [1, 2]])
b = np.array([[3, 4], [5, 9]])

a * b

array([[ 3,  8],
       [ 5, 18]])

### ii. Dot Product

Dot product is probably the most relevant kind of multiplication for our use cases. The dot product of matrices is also commonly known as **Matrix Multiplication**. Unless otherwise stated, _multiplication_ refers to this kind of multiplication.


\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\times
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} + a_{1,2}\times b_{2,1} & a_{1,1}\times b_{1,2} + a_{1,2}\times b_{2,2} \\
a_{2,1}\times b_{1,1} + a_{2,2}\times b_{2,1} & a_{2,1}\times b_{1,2} + a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}


We take the **rows** (horizontal) of the first matrix and do an element-wise product with the **columns** (vertical) of the second matrix. With this rule, what are the shape restrictions to doing matrix multiplication?

i.e. if we want to multiply matrices $A$ and $B$ where the dimensions of $A$ and $B$ are $m \times n$ and $p \times q$ respectively.

Using NumPy arrays, dot-multiply the matrices
\begin{bmatrix}
3 & 2 \\
5 & 7
\end{bmatrix}
\begin{bmatrix}
2 & 4 \\
3 & 10
\end{bmatrix}

in the code-cell below using `np.dot()`. Look up the documentation! Remember that you need square brackets around the whole array!

In [39]:
a = np.array([[3,2],[5,7]])
b = np.array([[2,4],[3,10]])
np.dot(a, b)

array([[12, 32],
       [31, 90]])

In [40]:
np.matmul(a, b)

array([[12, 32],
       [31, 90]])

Furthermore, $AB ≠ BA $  and $(AB)C ≠ A(BC)$.

In [41]:
np.dot(b, a)

array([[26, 32],
       [59, 76]])

### iii. Cross Product

The cross product is used for more abstract applications of linear algebra and here we'll just define it for vectors.

The result of the cross product of two vectors: $A \times B = |A||B|sin( \theta) n $
- ($n$ is the unit vector perpendicular to the plane formed by the two vectors)
- has a magnitude (length) equal to the area of the parallelogram formed by the two vectors
- perpendicular to the plane formed by the two vectors
- when you do a cross product, you lose a dimension


## d. Division

just kidding.

### Inverses and the Identity Matrix

It is **not** possible to divide by matrices (broadcasting still works element-wise). What we can do is find the **inverse** of a matrix. When a matrix is multiplied by its inverse, it results in the identity matrix. 

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/inverse.webp">

The order of multiplication does not matter for a matrix and its inverse:

$A \cdot A^{-1} = A^{-1} \cdot A $

An identity matrix is a square with a diagonal of 1's moving from left to right and the remaining numbers 0. When a matrix is multiplied by an identity matrix, it will result in the same matrix (think of it as the operational equivalent to 1 for linear algebra).

<img src = "https://raw.githubusercontent.com/yishuen/studygroups-092820ft/master/phase-3/resources/identity_matrix.svg">



In [42]:
# showing the effect of multiplying by the identity matrix

x = np.array([[4,8,10],[3,9,12],[5,10,15]])
i_3 = np.identity(3)

print(x, '\n')
print(i_3, '\n')
print(x.dot(i_3))

[[ 4  8 10]
 [ 3  9 12]
 [ 5 10 15]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ 4.  8. 10.]
 [ 3.  9. 12.]
 [ 5. 10. 15.]]


In [43]:
# inverse of x and multiplying by x

inv_x = np.linalg.inv(x)
print(inv_x, '\n')

print(np.round(x.dot(inv_x)))

[[ 0.5        -0.66666667  0.2       ]
 [ 0.5         0.33333333 -0.6       ]
 [-0.5        -0.          0.4       ]] 

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]


# Part 4: Systems of Linear Equations

One of the most common applications of matrix operations is in solving systems of linear equations. 
***
### Sidebar: What are Linear Equations?

Linear equations only have **linear variables**. This means our unknowns are only multiplied by a scalar and raised to a power of only **one**, such as:

$ x - 2y = 1$

$3ex + 2\pi y = 0$

**Not linear:**

$ x^2 - 2\ln{y} = 4$

$0.5x + 2y^x = 11$

$e^x + 2x=2$

***

To solve the system of linear equations to find `x` and `y`:

`x - 2y = 1`

`3x + 2y = 11`

First, we need to represent these equations as matrices/vectors.

$\begin{pmatrix}1 & -2 \\3 & 2 \end{pmatrix} \cdot \begin{pmatrix}x \\ y \end{pmatrix} = \begin{pmatrix}1 \\11\end{pmatrix}$ 

In [44]:
a = np.array([[1,-2],[3,2]])
b = np.array([[1],[11]])

*Isolate X!*

$\Large A \cdot X = B $

> *We'd like to divide, but that's not a thing!*
> 
>> *$\Large X = \frac{B}{A}$*

---

*Use the Inverse!*

$\Large A^{-1} A X = A^{-1} \cdot B  $

---

*$A^-1A$ always equals the Identity Matrix!*

$\Large I \cdot X   = A^{-1} \cdot B $

In [45]:
a = np.array([
    [1,-2],
    [3, 2]
])
b = np.array([
    [1],
    [11]
])

inv_a = np.linalg.inv(a)

inv_a.dot(b)

array([[3.],
       [1.]])

# Part 5: Linear Regression with Linear Algebra (OLS!)

A linear regression can be interpreted as the solution to a system of linear equations: each observation just corresponds to a linear equation, and the **coefficients** are the linear unknowns we're solving for! 

We're representing each **observation** as a **linear combination of features**.

Our prediction equation for a linear regression typically looks something like:

$\Large y_{pred} = \beta_{0} + \beta_{1}x_1 + \beta_{2}x_2 + ... + \beta_{n}x_n $

Represented in matrix form:

$\Large y = Xb $, so we are solving for $b$.

In this example, we'll work through a linear regression problem with the Auto dataset. We want to predict the **mpg** using *cylinders, displacement, horsepower, weight, acceleration and year*.

In [46]:
import pandas as pd
import seaborn as sns

In [47]:
car_df = sns.load_dataset('mpg').dropna()
car_df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [48]:
X_cols = [
    'cylinders',
    'displacement',
    'horsepower',
    'weight',
    'acceleration',
    'model_year'
]
X_df = car_df.loc[:, X_cols]
y = car_df['mpg']
X_df.head()

cylinders  displacement  horsepower  weight  acceleration  model_year
0          8         307.0       130.0    3504          12.0          70
1          8         350.0       165.0    3693          11.5          70
2          8         318.0       150.0    3436          11.0          70
3          8         304.0       150.0    3433          12.0          70
4          8         302.0       140.0    3449          10.5          70

In [49]:
# to get the intercept term
X_df['constant'] = 1

In [50]:
X_df.head()

cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8         307.0       130.0    3504          12.0          70   
1          8         350.0       165.0    3693          11.5          70   
2          8         318.0       150.0    3436          11.0          70   
3          8         304.0       150.0    3433          12.0          70   
4          8         302.0       140.0    3449          10.5          70   

   constant  
0         1  
1         1  
2         1  
3         1  
4         1

$ y = Xb + 0 $  --> $ y = Xb $

We want to solve for $b$! As we did before, to solve for $b$ we need to multiply both sides by the inverse of $X$.

Let's try to $ X^{-1} $


In [51]:
np.linalg.inv(X_df.values)

LinAlgError: Last 2 dimensions of the array must be square

We get: 

    LinAlgError: Last 2 dimensions of the array must be square.

We can only calculate an inverse of a **square** matrix. Why?

***

### Sidebar (again): Some Linear Algebra Theory 

In Linear Algebra theory, we have something called an **invertible matrix** with a definition as follows:

    An n-by-n square matrix A is called invertible if there exists an N by N square matrix B such that

<div style="text-align:center"><span style="color:blue; font-family:Georgia; font-size:1.5em;">AB = BA = I</span></div>

    where I is the identity matrix. A and B are inverses of each other.
    
***
    

By this definition, we can only find the inverse of square matrices. So with $b$ not being square, how can we solve this system using the data that we have? (No spoilers.)


$$b = (X^{T}X)^{-1}X^{T}y$$ 

---

1. Starting with $\large y = Xb$, however $\large X$ isn't a square, so we can't take the inverse of it.
    - **We can *make it square* by multiplying it by its own transpose.**


2. Left-multiply the transpose:
> $\large y = Xb$
>
> $\large X^Ty = X^TXb$
    - *Any time you multiply a matrix by its transpose, you are left with a square.*


3. We can isolate $\large b$ by multiplying $\large (X^TX)$ by the inverse of $\large (X^TX)$.
> $\large (X^TX)^{-1}X^Ty = (X^TX)^{-1}(X^TX)b$


4. We cancel out the *inverse of the square matrix* and the *square matrix itself* and are left with the above:
> $(X^{T}X)^{-1}X^Ty = b$
>
> $\LARGE b = (X^{T}X)^{-1}X^Ty$

Let's apply this to our data.

In [52]:
X = X_df.values
Xt = X.T
XtX = np.matmul(Xt, X)

product = np.matmul(np.linalg.inv(XtX), Xt)

b = np.matmul(product, y.values)
print(b)

[-3.29859089e-01  7.67843024e-03 -3.91355574e-04 -6.79461791e-03
  8.52732469e-02  7.53367180e-01 -1.45352505e+01]


Now we have our coefficients! They correspond to each of the columns in `X_df` in order. Let's compare this to our `sklearn` model.

In [53]:
list(zip(X_df.columns, b))

[('cylinders', -0.32985908907374784),
 ('displacement', 0.007678430243923874),
 ('horsepower', -0.00039135557375254496),
 ('weight', -0.0067946179133755325),
 ('acceleration', 0.08527324694732916),
 ('model_year', 0.7533671797501557),
 ('constant', -14.53525048051179)]

In [54]:
# comparing sklearn
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

skl_X = X_df.drop(columns = 'constant')
lr.fit(skl_X, y)

LinearRegression()

In [55]:
print('constant: ', lr.intercept_)
print('coefficients: ', lr.coef_)

constant:  -14.535250480506175
coefficients:  [-3.29859089e-01  7.67843024e-03 -3.91355574e-04 -6.79461791e-03
  8.52732469e-02  7.53367180e-01]


### Additional Resources
* 3 Blue 1 Brown:  https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_a
* Matrix approach to Linear Regression: http://www.stat.columbia.edu/~fwood/Teaching/w4315/Fall2009/lecture_11
* [link to fun desmos interaction](https://www.desmos.com/calculator/yovo2ro9me)
* [Link to good video on scalars and vectors](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
* [What is X^T * X?](https://stats.stackexchange.com/questions/267948/intuitive-explanation-of-the-xtx-1-term-in-the-variance-of-least-square/267963)